-- 코드를 작성해주세요'
WITH IT AS
(
    SELECT DISTINCT(ITEM_ID)
    FROM ITEM_TREE
    WHERE ITEM_ID NOT IN (SELECT IFNULL(PARENT_ITEM_ID, -1) FROM ITEM_TREE)
)
SELECT
    II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_INFO II, IT
WHERE II.ITEM_ID = IT.ITEM_ID
ORDER BY ITEM_ID DESC
