-- 코드를 입력하세요
WITH DP AS
(
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE IN ('SUV' , '세단') AND DURATION_TYPE LIKE '30일%'
)
SELECT C.CAR_ID, C.CAR_TYPE, ROUND(30*DAILY_FEE*(1-0.01*DP.DISCOUNT_RATE),0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
LEFT JOIN DP ON C.CAR_TYPE = DP.CAR_TYPE
WHERE (30*C.DAILY_FEE*(1-0.01*DP.DISCOUNT_RATE) BETWEEN 500000 AND 2000000) AND C.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE NOT(START_DATE > '2022-11-30' OR END_DATE < '2022-11-01')
)
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC

