-- 코드를 작성해주세요
WITH FE AS 
(
    SELECT CODE 
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)
SELECT
    DISTINCT(ID), EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS, FE
WHERE FE.CODE & SKILL_CODE
ORDER BY ID ASC