-- 코드를 작성해주세요
SELECT
HRE.EMP_NO, HRE.EMP_NAME,
(CASE WHEN AVG(HRG.SCORE)>= '96' THEN 'S'
    WHEN (AVG(HRG.SCORE)>= '90' AND AVG(HRG.SCORE) < '96') THEN 'A'
    WHEN (AVG(HRG.SCORE)>= '80' AND AVG(HRG.SCORE) < '90') THEN 'B' 
    ELSE 'C'
END) AS 'GRADE',
(CASE WHEN AVG(HRG.SCORE)>= '96' THEN HRE.SAL * 0.2
    WHEN (AVG(HRG.SCORE)>= '90' AND AVG(HRG.SCORE) < '96') THEN HRE.SAL * 0.15 
    WHEN (AVG(HRG.SCORE)>= '80' AND AVG(HRG.SCORE) < '90') THEN HRE.SAL * 0.1
    ELSE 0
END) AS 'BONUS'
FROM HR_EMPLOYEES HRE
JOIN HR_GRADE HRG WHERE HRE.EMP_NO = HRG.EMP_NO
GROUP BY HRE.EMP_NO
ORDER BY HRE.EMP_NO ASC