-- 코드를 작성해주세요
WITH PY AS 
(
    SELECT CODE 
    FROM SKILLCODES
    WHERE NAME = 'Python'
),
C AS 
(
    SELECT CODE 
    FROM SKILLCODES
    WHERE NAME = 'C#'
)
SELECT
    DISTINCT(ID), EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS, PY, C
WHERE PY.CODE & SKILL_CODE OR C.CODE & SKILL_CODE
ORDER BY ID ASC