-- 코드를 작성해주세요
SELECT
    SUM(GR.SCORE) AS SCORE, EM.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES EM
JOIN HR_GRADE GR ON EM.EMP_NO = GR.EMP_NO
WHERE GR.YEAR = '2022'
GROUP BY GR.EMP_NO
ORDER BY SCORE DESC
LIMIT 1