-- 코드를 작성해주세요
SELECT
    DE.DEPT_ID, DE.DEPT_NAME_EN, ROUND(AVG(EM.SAL), 0) AS AVG_SAL
FROM HR_DEPARTMENT DE
JOIN HR_EMPLOYEES EM ON EM.DEPT_ID = DE.DEPT_ID
GROUP BY DE.DEPT_ID
ORDER BY AVG(EM.SAL) DESC