WITH
PY AS (
    SELECT CODE
    FROM SKILLCODES 
    WHERE NAME = "Python"
),
C AS (
    SELECT CODE
    FROM SKILLCODES 
    WHERE NAME = "C#"
),
FE AS (
    SELECT SUM(CODE) AS CODE
    FROM SKILLCODES 
    WHERE CATEGORY="Front End"
)

SELECT 
    CASE
        WHEN SKILL_CODE & PY.CODE && SKILL_CODE & FE.CODE THEN 'A'
        WHEN SKILL_CODE & C.CODE THEN 'B'
        WHEN SKILL_CODE & FE.CODE THEN 'C'
    END as GRADE,
    ID, EMAIL
FROM DEVELOPERS, PY, C, FE
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID ASC